meta_product_name : "Doginder"
meta_title : "Doginder - pour houer a la baballe à plusieurs"
meta_description : "permet la sociabilisation de votre chien"
meta_image : "cover.png" # doit exister dans `app/assets/images/`
